### ISSUE TITLE
Reusing RichTextField in admin

### ISSUE THREAD

**Issue by bmihelac** [feincms/feincms#348]
In my opinion we should make changes to make recently introduced RichTextField easily reused outside FeinCMS inlines. 

Main reason is avoiding duplication of code needed to setup TinyMCE  (or other rich text editor) options.  For example if I override `ìnit.html`` to set up buttons, formats, and other settings, then I it would be great if  I dont have to do this once more in my other non FeinCMS models. 

As far as I investigated, this should  involve custom subclass of admin.ModelAdmin that would load jquery, tinymce and activate rich text as needed and configured.  

What do you think?

**Comment by matthiask** [comment]
I think we can close this. Many libraries appeared in the last ~10 years which address this issue in various nice ways.
