### ISSUE TITLE
TreeEditor pagination: Deactivate pagination, but find ways to not load really big trees upfront

### ISSUE THREAD

**Issue by matthiask** [feincms/feincms#504]

**Comment by sbaechler** [comment]
Maybe we can adapt part of the HSLU mobile nav code here. It does exactly that.

**Comment by matthiask** [comment]
Our tree code is quite fast with trees up to a few hundred nodes. 

Further improvements are probably best applied here: https://github.com/django-mptt/django-mptt/blob/9018e708f93de420f8c711a388d184e6963d3ab5/mptt/admin.py#L94
