### ISSUE TITLE
datepublisher_response_processor throws exception when publication_end_date is timezone aware

### ISSUE THREAD

**Issue by alastair-fah** [feincms/feincms#542]
If a page has a timezone-aware publication_end_date the datepublisher_response_processor will try to subtract datetime.now() from it and throw TypeError: can't subtract offset-naive and offset-aware datetimes, leading to a server error rather than  the desired page. Changing to timezone.now() fixes it for me, but I haven't tested it in other situations.

**Comment by matthiask** [comment]
Not sure whether this is fixed? It probably is...

Please reopen if not. Thanks!

**Comment by DrMeers** [comment]
I think this is fixed apart from the WARNING/TODO here -- https://github.com/DrMeers/feincms/blob/1707da9e884d1adbfc6911c71a1969abab8e1d89/feincms/module/extensions/datepublisher.py#L54

-- only occurs if the `make_aware` conversion results in a time which falls in the missing/extra hour during the night when daylight savings changes...
