### ISSUE TITLE
Media library: Suggest uploading JPEGs and/or PNGs when users upload TIFF files (but do not prevent upload)

### ISSUE THREAD

**Issue by matthiask** [feincms/feincms#543]
Maybe TIFF, BMP etc. should be treated as binary data instead :-)

**Comment by mjl** [comment]
Perhaps even try to do a dummy resize using sorl-thumbnail, and refuse stuff we cannot resize? I see all the time people uploading BMP or TIFF and things not working afterwards. While there, a post-upload-hook would be nice so one can strip metadata or stuff?

Most generic way would probably be a post-upload hook and you can then issue messages to the user or veto the upload.

**Comment by sbaechler** [comment]
In HTML5 the input[type=file] has an `accept` attribute. This could be used as a first gate to stop people from uploading PSD or TIFF files.

    <input type="file" name="media_empty" accept="image/gif,image/jpeg,image/jpg,image/png,">

**Comment by matthiask** [comment]
Yeah... we don't really want to stop people from uploading those files. We (did) want to warn them that those files will not be treated as images, but as downloads.

But that's probably all moot anyway, because we'll probably start using django-filer instead of feincms.module.medialibrary for present and future projects...

(Closing -- please reopen if you disagree.)
