### ISSUE TITLE
Thumbnail not working

### ISSUE THREAD

**Issue by nelsonvarela** [feincms/feincms#560]
Hi,

I am using FeinCMS and the build-in Medialibrary. The Medialibrary admin change list view is showing large images instead of thumbnails. 

Something is going wrong in the generate function of the default Thumbnailer:

    def generate(self, storage, original, size, miniature):
        try:
            image = Image.open(StringIO(storage.open(original).read()))

            # defining the size
            w, h = int(size['w']), int(size['h'])

            format = image.format # Save format for the save() call later
            image.thumbnail([w, h], Image.ANTIALIAS)
            buf = StringIO()
            if image.mode not in ('RGBA', 'RGB', 'L'):
                image = image.convert('RGBA')
            image.save(buf, format or 'jpeg', quality=80)
            raw_data = buf.getvalue()
            buf.close()

            storage.delete(miniature)
            storage.save(miniature, ContentFile(raw_data))

            return storage.url(miniature)
        except:
            # PIL raises a plethora of Exceptions if reading the image
            # is not possible. Since we cannot be sure what Exception will
            # happen, catch them all so the thumbnailer will never fail.
            return storage.url(original)

How can I figure out where the exception is being raised? And how come this code worked fine last years and now it is showing large images.

I am using FeinCMS 1.8.4 and above and django 1.6.5 and greater...

What alternatives are there to use as thumbnailer?

**Comment by mjl** [comment]
Basically the same already in in e873c4b.
