### ISSUE TITLE
Document how to do migrations in Django 1.7+

### ISSUE THREAD

**Issue by typeshige** [feincms/feincms#564]
I'm trying to figure out of it's possible to migrate my Page content types.

I don't think it's documented but it seems like it should be possible.

There was a bit in the documentation about how to use South with FeinCMS but it hasn't been updated for the built-in migrations in Django 1.7+.

**Comment by FrancoisConstant** [comment]
It seems that you just need to use MIGRATION_MODULES instead of SOUTH_MIGRATION_MODULES.

For example:
MIGRATION_MODULES = {
        'page': 'cms.migrate.page',
    }

**Comment by michaelkuty** [comment]
+1 to update doc with new tested workaround

**Comment by bartTC** [comment]
Note that you have to set the *full* dotted path to the application, ending with the `migrations` folder. 

```
    'page': 'project.apps.mycms.migrations'
```

**Comment by matthiask** [comment]
Thanks, all!

**Comment by nelsonvarela** [comment]
Can anyone explain how to get this working in steps. I've just created the migration directories, added the setting and ran makemigrations but the only message is got is: 'No changes detected in app 'pages'.

I am trying to make an initial migation file for an existing app (project was build with django 1.5 and is now working with 1.7).

**Comment by michaelkuty** [comment]
please check if you have properly created directories with __init__.py files if you use python < 3
next you must set migration modules which says where will be lives your migrations as mentioned in @bartTC post

MIGRATION_MODULES = {
    'page': 'project.apps.mycms.page_migrations'
}

for sure add these lines on top of your settings.py file
