### ISSUE TITLE
Table of FeinCMS <-> Django version requirements

### ISSUE THREAD

**Issue by barseghyanartur** [feincms/feincms#565]
It would be great to have a table overview of FeinCMS <-> Django version requirements.

Otherwise, a question - does FeinCMS 1.4.2 work well with Django 1.4.2?

**Comment by sbaechler** [comment]
I started a compatibility table here: https://docs.google.com/spreadsheets/d/1w1Gix3q4pNtyBJ0RwNOPpLQpEakvxxChadv3LK_Uy70/edit?usp=sharing.

**Comment by barseghyanartur** [comment]
@sbaechler 

Awesome!

**Comment by matthiask** [comment]
The pull request has been merged. Thanks!
