### ISSUE TITLE
Medialibrary has a dependency on the Site framework.

### ISSUE THREAD

**Issue by sbaechler** [feincms/feincms#573]
The function `save_as_zipfile` in `feincms/module/medialibrary/modeladmins.py` has a dependency on the Sites framework. If `django.contrib.sites` is not installed, a server error is thrown if a user uploads a zip file.

**Comment by sbaechler** [comment]
The bug has most likely been fixed in this commit: https://github.com/feincms/feincms/commit/b6572533e7f3380f5e080d3b4a862116d21a805c.

**Comment by matthiask** [comment]
Yes. Thanks!
