### ISSUE TITLE
FEINCMS_CMS_404_PAGE doesn't seem to be working

### ISSUE THREAD

**Issue by paramono** [feincms/feincms#575]
I am trying to use FEINCMS_CMS_404_PAGE, however, I get the django's message "The requested URL was not found on this server." instead.

It is also unclear from the documentation how exactly to use this option. I found the code that handles  FEINCMS_CMS_404_PAGE [here](https://github.com/feincms/feincms/blob/master/feincms/views/cbv/views.py). Does this option work?

**Comment by mjl** [comment]
> I am trying to use FEINCMS_CMS_404_PAGE, however, I get the django's message "The requested URL was not found on this server." instead.
> 
> It is also unclear from the documentation how exactly to use this option. I found the code that handles FEINCMS_CMS_404_PAGE here. Does this option work?
> 
Yes it should work, however I remember having changed stuff in that part of the code recently, check the "next" branch, though it should only affect you if using redirects.


To answer the usage question, you should have a cms page at a certain path (let's say /error), then you put 
FEINCMS_CMS_404_PAGE = "/error"

in your settings.py -- the 404 will then come with that page as body.

**Comment by paramono** [comment]
Hm, that's exactly how I tried to use it. Though I designed a page with a slug of "404", and tried to reference it with FEINCMS_CMS_404_PAGE = "/404", to no avail.

I've actually seen this fixed code in the next branch, thanks for pointing it out! I tried monkey-patching my virtual environment with your views.py; though, in my case, http404 is always being thrown and I get "Http404 raised while resolving FEINCMS_CMS_404_PAGE=%s" message from the logger.

Is it going to work if my 404 page's parent has an url override? ("/"). Are there any other things I may be missing?

**Comment by paramono** [comment]
I cannot use the code from the **next** branch directly because I cannot import
`from feincms._internal import get_model`

So instead I simply copied your `dispatch` method. It didn't work as it is; so instead I removed the "/" override from the index page, and it worked! The problem is, I really do need that override for the index page.

Now my question is: is it possible to make it work when I do have an URL override? Otherwise the logger simply outputs that "/error/" cannot be found

**Comment by mjl** [comment]
An override should not really hurt, but it obviously does. Have you tried moving your error page _under_ the root-overriding page, perhaps the override is grabbing all requests for /something and distributes it to its children? Just a vague idea something like that might happen...

**Comment by paramono** [comment]
I have an index page with a "/" override. views/cbv/views.py is partially monkey-patched with code from the **next** branch (`dispatch` method is replaced and logger is imported). The error page has "error" slug, FEINCMS_CMS_404_PAGE is defined as "/error/". I tried accessing non-existent page under following conditions:

1. Error page is located outside of the index page (thus making them "siblings"). I got: `The requested URL /error/ was not found on this server.` (it doesn't matter which url I enter, as long as it doesn't exist).
2. Error page is placed under the index page (index page becomes a parent of the error page). I get exactly same error: `The requested URL /error/ was not found on this server.`

It is possible to access /error/ directly, though error page is not displayed when non-existent page is requested. The issue is resolved when url override is removed, but I am looking for a way to make it work with the url override in place. 

>perhaps the override is grabbing all requests for /something and distributes it to its children?

This seems to be happening in both cases, though. Is there any simple way to fix that?

**Comment by mjl** [comment]
Could you try to add the small patch in 6ae6517 in your version and see whether that fixes the problem? It did for me.

**Comment by paramono** [comment]
I tried the patch: yes, it fixes the problem! Thanks!

**Comment by mjl** [comment]
Yeah! Thanks for your help!
