### ISSUE TITLE
PIL is deprecated and unsupported in in Django 1.8 -> switch to Pillow

### ISSUE THREAD

**Issue by nanuxbe** [feincms/feincms#583]
PIL support should have been dropped in Django 1.8 as stated here https://docs.djangoproject.com/en/1.8/releases/1.8/#features-removed-in-1-8

We should switch to Pillow as well

References https://github.com/feincms/feincms/issues/574

**Comment by matthiask** [comment]
Thanks for the report. Pillow is imported using `from PIL import Image` as well, or does Pillow have a different top-level package name too?

The dependency in `setup.py` also references Pillow, not PIL: https://github.com/feincms/feincms/blob/master/setup.py#L43

**Comment by nanuxbe** [comment]
Sorry, my bad. It clearly depends on Pillow, not PIL, while trying to reproduce some other bug I just ran into a "No module named 'PIL'" Exception that threw me off and thought it would be better to catch the exception and mention Pillow.
But this can actually only happen if running from source without having run setup.py on that environment, so it's not an issue

**Comment by matthiask** [comment]
Thanks!
