### ISSUE TITLE
Admin: Template change message contains HTML

### ISSUE THREAD

**Issue by bartTC** [feincms/feincms#584]
When changing a template the warning alert box contains HTML

![20962030-e1d1-11e4-8bc9-9c54d4410ee8](https://cloud.githubusercontent.com/assets/1896/7269329/4195f7ac-e8d3-11e4-864c-b508efecdf09.png)

![687474703a2f2f642e70722f692f3138426f562e706e67](https://cloud.githubusercontent.com/assets/1896/7269317/26d6e28c-e8d3-11e4-99e7-9ce988728288.png)

**Comment by matthiask** [comment]
Thanks. I obviously haven't completely removed all traces of the old jQuery alert box implementation.

**Comment by matthiask** [comment]
Will be fixed in FeinCMS 2.0 (see commit above)
