### ISSUE TITLE
Deleted checker.py file is still present in FeinCMS-1.11.0-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by pzrq** [feincms/feincms#586]
Discovered it because a team member still had `pip==1.4.1` on their local machine which doesn't seem to use `.whl` files and we were for some unknown reason still importing it where we shouldn't have. 

`pip==6.0.8` and `pip==6.1.1` were fine if they installed from the `.whl` file.

Deleted `feincms/management/checker.py` here: https://github.com/feincms/feincms/commit/ead3c0209fab20e341d0f7ddc865bf0991fe248d

@matthiask I guess you should look into how deleted files could still end up in `FeinCMS-1.11.0-py2.py3-none-any.whl`.

**Comment by matthiask** [comment]
@pzrq Thanks for the report. Does the existence of this file lead to problems or is it just a nuisance? 

If it's the former, please explain. I'll fast-track a patch release if necessary.

**Comment by pzrq** [comment]
@matthiask No problems here either way (we didn't need it so just removed the import).
Just letting you know for your normal release cycle, feel free to close this when you do the next release.

**Comment by matthiask** [comment]
I see, thanks for letting me know!

**Comment by matthiask** [comment]
Fixed in v1.11.1
