### ISSUE TITLE
Migrations support in documentation

### ISSUE THREAD

**Issue by atleta** [feincms/feincms#587]
Hi,

I've just tried adding migrations (1.7+) support, but the documentation ( http://feincms-django-cms.readthedocs.org/en/latest/migrations.html ) is wrong. First of all, the django 1.7+ part doesn't explain what directory you'll need to create (should be migrate, according to the example).

Then, I think using the app name 'page' will lead to errors (and confusions). I'd suggesting using 'yourapp_page' *and explaining what it is* (also, yourapp_medialibrary)

Third: it misses a crucial step, actually creating the initial migrations:
./manage.py makemigrations yourapp_page
./manage.py makemigrations yourapp_medialibrary

**Comment by atleta** [comment]
Hmm... and then, migrations being end up created in the feincms module directory (inside the virtualenv), which is pretty much useless, as the virtualenv doesn't get deployed. :-/

**Comment by michaelkuty** [comment]
#591

**Comment by matthiask** [comment]
Fixed in e38bffcb423d74a8f784993f260ce333be036795. Thanks for the report and pull request!
