### ISSUE TITLE
When selecting a page via a raw_id_field in the admin the expand/collapse arrows don't work

### ISSUE THREAD

**Issue by svleeuwen** [feincms/feincms#594]
The function `dismissRelatedLookupPopup` is called before `expandOrCollapseNode`. Hence the popup closes before the list is expanded/collapsed.

Is this fixable? Is there a workaround?

**Comment by matthiask** [comment]
Not sure -- I tested this today, but had the impression that the bug was fixed or somehow disappeared??

**Comment by svleeuwen** [comment]
Yes, I can't reproduce it anymore too. Could have been an exceptional use case...

**Comment by matthiask** [comment]
Great, thanks for confirming.
