### ISSUE TITLE
ImportError: No module named v2

### ISSUE THREAD

**Issue by chrisspen** [feincms/feincms#598]
[Current docs](http://feincms-django-cms.readthedocs.org/en/latest/medialibrary.html) say to import MediaFileContent like:

    from feincms.content.medialibrary.v2 import MediaFileContent

However, this gives me the error:

    ImportError: No module named v2

I'm using FeinCMS==1.10.1 and Django==1.5.5 (due to other dependencies, I can't upgrade to Django>=1.6).

**Comment by matthiask** [comment]
Oh yes, that's bad. You get better results importing from `feincms.content.medialibrary.models` with said Django version. Sorry!
