### ISSUE TITLE
Content does not get correctly saved, double save needed

### ISSUE THREAD

**Issue by mattiasculpteo** [feincms/feincms#602]
Hi, I am having a problem with the feincms:

I would like to add an extra line into the "head" field of my html pages contained into the cms.
In order to achieve this i use the following lines (we suppose page object has been correctly found previously in the code):

                raw_content = page.content_type_for(RawContent)
                raw_object = raw_content.objects.get_or_create(parent_id=page.id, region='head')[0]
                raw_object.text = "<a href .... />" (let's say I am adding a link)
                raw_object.save()

Problem is: when visiting the webpage, the line I just added does not appear inside the html source code. Instead, if I check on the page content through feincms admin interface, I can see that everything looks fine, the new line correctly appears inside the "head" field of my page. Now if I click on "save and continue editing" from the interface, the page gets saved again (because I already saved it with my script) and now the new line can be seen into the html code ...  

Thanks for your time, have a nice day

**Comment by mjl** [comment]
I suppose the content type cache is the culprit. You would need to null out page._ct_inventory so feincms picks up something has changed.

**Comment by matthiask** [comment]
Too much non-obvious caching deep inside FeinCMS.

**Comment by matthiask** [comment]
Fixed in `next`
