### ISSUE TITLE
Question about the translation

### ISSUE THREAD

**Issue by FrancoisConstant** [feincms/feincms#605]
In the documentation, this is mentioned:

http://feincms-django-cms.readthedocs.org/en/latest/page.html
feincms.module.extensions.translations — Page translations

Adds a language field and a recursive translations many to many field to the page, so that you can define the language the page is in and assign translations. I am currently very unhappy with state of things concerning the definition of translations, so that extension might change somewhat too. [...]

What are the issues with the current implementation?

**Comment by matthiask** [comment]
Oh, that's a really old comment right there.

The extension works well enough. The biggest problem with it is that the tree structure has to be maintained for each and every translation by hand. Most often with multilingual sites the page tree is more or less the same.

When this extension was initially written I assumed (incorrectly) that pages would only be maintained well in the primary language, and translations would lag far behind. 

I currently do not have any plans to revise this extension, so I could just as well drop this comment.

Thanks!
