### ISSUE TITLE
Django 1.9 support?

### ISSUE THREAD

**Issue by LegoStormtroopr** [feincms/feincms#606]
Django 1.9 is now officially out, is this on the near roadmap for feincms?

I'm getting an immediate bug after an upgrade:

```
  File "/home/ubuntu/workspace/parlhand/extra/pages/pages.py", line 31, in <module>
    ('main', _('Main content area'), 'inherited'),
  File "/usr/local/lib/python2.7/dist-packages/feincms/models.py", line 425, in register_templates
    field.default = field.choices[0][0]
IndexError: list index out of range
```

When calling this code which worked previously:
```
Page.register_templates({
    'title': _('Standard template'),
    'path': 'cms_page/page.html',
    'regions': (
        ('main', _('Main content area'), 'inherited'),
        #('sidebar', _('Sidebar'), 'inherited'),
    ),
},
{
    'title': _('Full page template'),
    'path': 'cms_page/fullpage.html',
    'regions': (
        ('main', _('Main content area'), 'inherited'),
        #('sidebar', _('Sidebar'), 'inherited'),
    ),
})
```

And printing `field` and `field.choices` gives:

```
page.Page.template_key []
```

**Comment by sspross** [comment]
+1

@LegoStormtroopr as @matthiask pointed out, the next branch fixes this issue, see https://github.com/feincms/feincms/commit/7e09d9c821d9dbd72cf60c19708f91a3248d3b95

**Comment by matthiask** [comment]
Thanks. The next branch also contains many unrelated changes which will certainly break everyone's code.

We are working on a patch release for 1.11.x which will solve those issues soon, hopefully.

**Comment by matthiask** [comment]
Progress here: https://github.com/feincms/feincms/tree/next_1.x

**Comment by LegoStormtroopr** [comment]
Thanks for the update @matthiask . FeinCMS is great :D

Having looked at a number of other packages, Django1.9 migration will be a slow process for a lot of people.

**Comment by matthiask** [comment]
One of the problems we're facing is that there is no Django 1.9-compatible release of django-mptt yet.

(Help wanted! https://github.com/django-mptt/django-mptt/issues/415)

**Comment by sspross** [comment]
@matthiask thanks for your (fast) work on 1.11.12! are you taking about `<class 'feincms.module.page.modeladmins.PageAdmin'>: (admin.E023) The value of 'radio_fields' refers to 'template_key', which is not an instance of ForeignKey, and does not have a 'choices' definition.`?

**Comment by matthiask** [comment]
Damn. Django really does not make it easy.

Try 1.11.3 :-) please.

**Comment by sspross** [comment]
looks good! thx a lot, now it's up to mptt :)

**Comment by matthiask** [comment]
Great! So, let's close this issue :)
