### ISSUE TITLE
Regression with recent admin.E023 error fix.

### ISSUE THREAD

**Issue by joshuajonah** [feincms/feincms#608]
8e43e13fc218b61f6a83a50eb682fc12e8274ed3 introduced a validation error when creating a page in the admin.

![validation failure](http://i.imgur.com/psiNtJl.png)

**Comment by joshuajonah** [comment]
This is on a clean install with only feincms (master, next_1.x, or next with this change applied). My `register_templates` is pretty basic as well:

    Page.register_templates(
        {
            'title': _('Base'),
            'path': 'base.html',
            'regions': (
                ('main', 'Main content area'),
            ),
        },
        {
            'title': _('Single Column'),
            'path': 'basic.html',
            'regions': (
                ('main', 'Main content area'),
            ),
        },
    )

**Comment by matthiask** [comment]
Thanks, also for the pull request! Unfortunately your PR fails with Django 1.9.

I think I've found the reason for this failure, a fix is here: https://github.com/matthiask/feincms/commit/4740409b459ba1680fdab9780d73c3828feeb698 — let's see what Travis says.

**Comment by joshuajonah** [comment]
Cool, that works. Thanks.

**Comment by matthiask** [comment]
You're welcome!
