### ISSUE TITLE
Django 1.9 upgrade issues

### ISSUE THREAD

**Issue by mvcoding** [feincms/feincms#619]
I tried to upgrade to Django 1.9 these days and stumbled across two issues:

Using the german locale, the admin panel gets broken. You cannot edit pages, a JS error prevents the use of some controls there. The pull https://github.com/feincms/feincms/pull/618 should solve that.

The second one may not be related directly to FeinCMS. With Django 1.8 i could use unescaped html input in my custom content type, but in 1.9 it gets escaped automatically and i dont know how to change that.

**Comment by matthiask** [comment]
Thanks for the pull request! Great work.

Regarding the second issue: Django's `simple_tag` has started to escape content in 1.9 (https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape). This should be handled by https://github.com/feincms/feincms/commit/a11633a3e5a27c2a22f310980548d9726208f7af 

Maybe you are missing a `mark_safe` somewhere? Or maybe there's still a bug in FeinCMS...

**Comment by mvcoding** [comment]
You are welcome. We have to thank sha-red for the actual commit though.

Thanks for pointing out the escaping change. I use a simple TextField for inputs in my content type. Guess the mark_safe is missing for the return value in the render method there. I will try that and see if it works.

**Comment by matthiask** [comment]
Any success @mvcoding ?

**Comment by mvcoding** [comment]
Yes, with both.

Wrapping the return value of the content type in mark_safe fixed the escaping problem and with the updated german locale the admin panel is working again.

**Comment by matthiask** [comment]
Awesome! Thanks for the confirmation.
