### ISSUE TITLE
Unable to pull in object content with a post save signal. FeinCMS 1.11.4

### ISSUE THREAD

**Issue by jsqho** [feincms/feincms#623]
So briefly, my issue is that I'm attempting to grab an instance's content types during a post save signal. In my case, I have an Article Model that has a lot of different content types tied to it via the FeinCMS e.g. Markup Text, Image, and etc.. And when I attempt to access this during the save process, they don't exist yet, but after the actual entire object save, they are there, and I want to be able to pull in these content types because I'm syncing the rendered html from each of these content types to another model and app.

Any insight or tips would be great.

Thanks!

**Comment by mjl** [comment]
You probably want the m2m_changed signal instead of post_save, see https://docs.djangoproject.com/en/1.9/ref/signals/#django.db.models.signals.m2m_changed

  I also seem to remember we emit a custom signal in feincms for that, but I might be wrong here, it just sounds familiar...

        mjl

**Comment by matthiask** [comment]
Indeed. If you're using the ItemEditor, you can listen to `feincms.signals.itemeditor_post_save_related`, or simply override `ModelAdmin.save_related` (historical note: this particular method was not available when the signal was added, now both ways are equivalent.)

**Comment by jsqho** [comment]
Sounds good. I'll give it a shot and report back in if it's a viable solution to my problem. And thanks!

**Comment by jsqho** [comment]
Great news. Using the save_related from the ModelAdmin gave me exactly the attributes I needed. Thanks @matthiask  and @mjl for the nudge in the right direction. Also, for the item_editor_post_save_related, I couldn't find any real documentation for it, so just wanted to let you know just in case someone else might want access to it. Thanks again!
