### ISSUE TITLE
Suggestion - Sample feincms page app as in DOC screenshot

### ISSUE THREAD

**Issue by sunjoomoon** [feincms/feincms#624]
Wondered if cms sample as per http://feincms-django-cms.readthedocs.org/en/latest/ screen shot is available anywhere at all. I am trying out installation and having challenging time. Feel like fluent page and feincms are similiar in many ways though. Fluent pages was easy to install and configure all following the doc. But I really want to give feincms a good try.

**Comment by matthiask** [comment]
Hey Sunjoomoon,

Unfortunately there's no ready-made example project available right now. feincms-in-a-box might help there, please report back if this works for you. https://feincms-in-a-box.readthedocs.io/en/latest/
