### ISSUE TITLE
Installation issues with Django 1.9

### ISSUE THREAD

**Issue by mpauly** [feincms/feincms#625]
When installing FeinCMS on Django 1.9 unfortunately the relevant tables for the pages application are not created automatically for me. All tables page_* are missing. Downgrading to Django 1.8, creating the tables, and then switching back to 1.9 resolves this issue, but isn't really a proper solution.
I create the tables using manage.py migrate

Am I doing something wrong here? Probably the problem might be related to migrations support in FeinCMS?

**Comment by matthiask** [comment]
Hmm... FeinCMS does not do anything special when it comes to migrations... I don't quite see why `page_page` would not be created.

You only write about `manage.py migrate` — what about `makemigrations`? Are the initial migrations there? Did you run `./manage.py makemigrations page` first?

**Comment by mpauly** [comment]
Ah seems this was my mistake - I did not get that the migrations had to be created for the page module - just tried it for feincms itself, but it totally makes more sense for the page module. I dont really see why it worked in 1.8 however, but anyways seems like I can solve my problem.
Thank you and sorry for bothering...

**Comment by matthiask** [comment]
No bother at all. Great to hear that everything works now!

On Sat, Mar 5, 2016 at 10:38 AM, mpauly <notifications@github.com> wrote:

> Closed #625 <https://github.com/feincms/feincms/issues/625>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feincms/feincms/issues/625#event-578740731>.
>



-- 
Matthias Kestenholz
Partner, Programmierung

FEINHEIT AG
Molkenstrasse 21
8004 Zürich
www.feinheit.ch

**Comment by matt-snider** [comment]
I followed the installation instructions and have the same issue. It's unaffected by `makemigrations` because in both versions of Django, no migration files are created. I'm using Python 3.5, FeinCMS 1.12.1 and Django 1.9.6.

I created a new project and app to test it out with the different versions of Django. 

Starting with Django 1.9
```console
$ python manage.py makemigrations
No changes detected

$ python manage.py migrate
Operations to perform:
  Apply all migrations: contenttypes, auth, admin, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK

$ echo "SELECT name FROM sqlite_master WHERE type='table';" | python manage.py dbshell
django_migrations
sqlite_sequence
auth_group
auth_group_permissions
auth_user_groups
auth_user_user_permissions
django_admin_log
django_content_type
auth_permission
auth_user
django_session
```

I then downgraded to Django 1.8 and removed the db. I didn't paste output as it was all as expected
```console
$ pip uninstall django
$ pip install django==1.8
$ rm db.sqlite3
```

Now the same commands as before:
```console
$ python manage.py makemigrations
No changes detected

$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: medialibrary, mptt, feincms, staticfiles, messages, page
  Apply all migrations: admin, sessions, contenttypes, auth
Synchronizing apps without migrations:
  Creating tables...
    Creating table page_page
    Creating table page_page_richtextcontent
    Creating table medialibrary_category
    Creating table medialibrary_mediafile
    Creating table medialibrary_mediafiletranslation
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK

$ echo "SELECT name FROM sqlite_master WHERE type='table';" | python manage.py dbshell
django_migrations
sqlite_sequence
page_page
page_page_richtextcontent
medialibrary_category
medialibrary_mediafile
medialibrary_mediafile_categories
medialibrary_mediafiletranslation
auth_group
auth_group_permissions
auth_user_groups
auth_user_user_permissions
django_admin_log
django_content_type
auth_permission
auth_user
django_session
```
Have you got any ideas on what's going on here? Is there something I'm missing?

Note that there is also this error following any manage.py command when using Django 1.9, but I could open another issue for this:
```
<path-to-python>/python3.5/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)
```

**Comment by matt-snider** [comment]
I was looking around trying to find the cause of this, and found this in the [release notes for Django 1.9](https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9): 

 * Automatic syncing of apps without migrations is removed. Migrations are compulsory for all apps unless you pass the migrate --run-syncdb option.

Indeed, if run with the `--run-syncdb` option, the necessary migrations are created. It does seem like this should be documented, or the migrations should be defined as recommended by Django

**Comment by matthiask** [comment]
Yeah, you have to explicitly make migrations for the `page` app the first time. 

https://feincms-django-cms.readthedocs.io/en/latest/migrations.html

(1. set `MIGRATION_MODULES` 2. run `./manage.py makemigrations page`)

**Comment by matt-snider** [comment]
Hi, thanks for the response!

As I've shown above, this behaviour is vastly different for Django 1.8/1.9. For 1.8, the `MIGRATION_MODULES` setting is not needed, as simply running `migrate` will do the trick.

For 1.9, I've tried the above from the migrations documentation, and it results in `ImportError: No module named myapp.migrate.page`. This only works for me when I create the entire directory structure including the `page` package. This is pretty surprising considering the [Django documentation](https://docs.djangoproject.com/en/1.9/ref/settings/#migration-modules) seems to indicate that it will create the package. This might be something to clarify in the docs
