### ISSUE TITLE
FeinCMS version 2

### ISSUE THREAD

**Issue by pyzenberg** [feincms/feincms#629]
I'm starting a new project and found FeinCMS the only CMS on Django planet which is based on content blocks (like the good old django-cms, I hate inline editing).

While installing it, noticed on pypi that the are a bunch of (probably alpha) packages with v2 signatures which I couldn't manage to find proper documentation or roadmap.

Is it still safe enough to use those ones instead of official 1.x line? What's the significant differences between them? Is there a place to find notes about them?

Thank you.

**Comment by mjl** [comment]
Currently 1.11.4 is the latest released version; please use that. If you want you can use the "next" branch from git for the absolutely latest development version, but it requires Django 1.7+ (or use the branch "next_1.x" which I'll try to somewhat maintain as long as I need a Django 1.6 compatible version).

  And: Welcome to the club, please give use feedback on your journey!

**Comment by pyzenberg** [comment]
Thanks for the lightning fast response! I want to use FeinCMS with Django 1.9. Usually I make an adventure with the development version and if time gets short I switch to the stable version.

It would be honour to be useful on this project. Cheers!

**Comment by matthiask** [comment]
FeinCMS 2 was a failed (IMO) attempt at cleaning up some of the less beautiful parts of feincms. It contained too many breaking changes without enough upsides to compensate for this.

I'll continue with FeinCMS 1.x for now.

**Comment by matthiask** [comment]
Just a heads up: 1.12 has been released a few days ago.

**Comment by matthiask** [comment]
FeinCMS 1 is fine as it is; there's no need to think about big, breaking changes from my point of view right now. I'm closing this issue for now. Thanks!
