### ISSUE TITLE
Tag feincms_parentlink missing after upgrade to FeinCMS 1.12.0

### ISSUE THREAD

**Issue by martinsabo** [feincms/feincms#630]
Cannot load feincms_parentlink tag after upgrade of FeinCMS from version 1.11.4 to 1.12.0. Whole error message in my case is:

"Invalid block tag on line 52: 'feincms_parentlink'. Did you forget to register or load this tag?"

Tags are loaded in template with:

"{% load applicationcontent_tags feincms_tags feincms_page_tags i18n %}"

According to docs the tag should be still supported,  but I can't find him in the installed FeinCMS sources.

Any ideas?

Thank you.

Martin

**Comment by matthiask** [comment]
Thanks for the report! Fixed in v1.12.1.
