### ISSUE TITLE
Support content security policy in Django 1.10

### ISSUE THREAD

**Issue by graingert** [feincms/feincms#632]
Currently Fein CMS uses inline JS for customisation and Django->JS communication this should be replaced with JSON parsing etc to allow for unsafe-inline to be disabled.

**Comment by matthiask** [comment]
Good point.

(django-mptt's DraggableMPTTAdmin (http://django-mptt.github.io/django-mptt/admin.html#mptt-admin-draggablempttadmin) and django-content-editor (https://github.com/matthiask/django-content-editor) already are CSP-compatible. We should probably (re)build on top of those.)

**Comment by macolo** [comment]
any updates on this one?

**Comment by matthiask** [comment]
No, nobody's actively working on this right now.

**Comment by matthiask** [comment]
Nothing has changed. Closing this because nobody's working on it and it's not probable anyone will (on FeinCMS 1.x)
