### ISSUE TITLE
subdomain redirect

### ISSUE THREAD

**Issue by nelsonvarela** [feincms/feincms#634]
HI,

I have a website on subdomain.example.com. When I use the redirect_to on a page to another page in the site the user is redirected to example.com instead of subdomain.example.com.

Is this a known issue?

**Comment by matthiask** [comment]
Hey,

are you using `django.contrib.sites` by chance? This might have something to do with it. AFAIK we aren't doing anything special with redirects, the code *should* simply redirect to `get_absolute_url()`.

**Comment by nelsonvarela** [comment]
Sites is enabled (as in listed in installed apps) but i am not using it. Just one record with example.com in it. Indeed you are not doing something special with redirects. I'm still looking at this and hope I will find the problem soon (or someone with the answer).

**Comment by mjl** [comment]
I'd suggest trying putting your real domain in the sites table and see if that changes things. The absolute url builder might reference that if the sites app is loaded.

        mjl

**Comment by nelsonvarela** [comment]
I had multiple server_name's in my nginx config and the first one was the one without the subdomain. Somehow nginx redirects to the first domain listed in server_name

**Comment by matthiask** [comment]
Good to hear that it works now!

(I've never heard of the nginx behavior you mention, but don't know nginx that well. Still, I suspect there's something else going on.)
