### ISSUE TITLE
Duplicate/obsolete documentation on http://feincms.readthedocs.io/

### ISSUE THREAD

**Issue by sha-red** [feincms/feincms#635]
There is an old an obsolete documentation website at http://feincms.readthedocs.io/ which should be deleted or redirected to the newer http://feincms-django-cms.readthedocs.io/ ,

**Comment by matthiask** [comment]
Thanks for the report. That's a known issue. I sent some mails to rtd and to the guy who registered the feincms project to rtd years ago and unfortunately didn't receive any answers. I should probably try again. In the meantime there's also https://feincms-django-cms.readthedocs.io/en/latest/.

**Comment by matthiask** [comment]
I just noticed that it's sufficient to kick off a new build here: http://readthedocs.org/projects/feincms/builds/
