### ISSUE TITLE
Remove references to SubfieldBase

### ISSUE THREAD

**Issue by ebrelsford** [feincms/feincms#636]
`SubfieldBase` was removed in Django 1.10, FeinCMS uses it in [JSONField](https://github.com/feincms/feincms/blob/master/feincms/contrib/fields.py#L33). Would be awesome if we could fix this and upgraded to Django 1.10.

**Comment by b45ch1** [comment]
I have the same issue. 
```
August 05, 2016 - 15:49:06
Django version 1.10

...

from feincms.contrib.fields import JSONField
  File "web/virtualenv/local/lib/python2.7/site-packages/feincms/contrib/fields.py", line 33, in <module>
    class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: 'module' object has no attribute 'SubfieldBase'

```

**Comment by b45ch1** [comment]
I have added a partial fix https://github.com/hekori/feincms/commit/409669dee9a148e3d6bfd0bd0f5ed90942990f6d

I did not run any tests or took backward compatibility into consideration.

**Comment by matthiask** [comment]
Thank you! We should at least keep compatibility with Django 1.8, since that's a LTS release (I think).

**Comment by b45ch1** [comment]
I have added a PR  https://github.com/feincms/feincms/pull/637

Please have a look at the way I have changed the code of ``render_to_string``. I'm not sure if I correctly pass on the information in ``kwargs.get('context')`` (the unit tests work, though).

**Comment by matthiask** [comment]
Thanks. Fixed in https://github.com/feincms/feincms/tree/next. I'll have to roll another release soon.
