### ISSUE TITLE
DeprecationWarning: extensions

### ISSUE THREAD

**Issue by nelsonvarela** [feincms/feincms#643]
It says:

DeprecationWarning: Import feincms.module.extensions.datepublisher from feincms.extensions.feincms.module.extensions.datepublisher

But the correct path is:
feincms.extensions.datepublisher

**Comment by virsystem** [comment]
\virtenvs\django\lib\site-packages\feincms\extensions\base.py", line 50, in register_extensions
    ext, cls.__name__))
django.core.exceptions.ImproperlyConfigured: extensions.datepublisher is not a valid extension for Page

models from tutor

**Comment by matthiask** [comment]
Fixed in https://github.com/feincms/feincms/commit/bc606fdd9989289d697094ed9f64a6d4a25c7048. Thanks!
