### ISSUE TITLE
Override _page_title max_lenght

### ISSUE THREAD

**Issue by POD666** [feincms/feincms#646]
I have tried to create extension:
```
class Extension(extensions.Extension):
    def handle_model(self):
        self.model._meta.get_field('_page_title').max_length = 100
        self.model._meta.get_field('_page_title').help_text = (
            'Page title for browser window. Same as title by default. Must be 100 characters or fewer.'
        )
```
but when I save page instance in admin interface I get warning that length should be <69.
![scr](https://cloud.githubusercontent.com/assets/5798108/22510815/07a036a0-e89c-11e6-8b96-ce1c99be26c9.png)

How can I deal with it?

**Comment by matthiask** [comment]
I'm not sure why the patching does not seem to have an effect.

The simplest way is probably to copy the whole `titles.py` extension file into your project, and load your own version.

**Comment by matthiask** [comment]
Maybe Django autogenerates validators to check the length? Maybe the field instance has a `validators` attribute containing a `MaxLengthValidator` which should be replaced as well.

**Comment by matthiask** [comment]
... that being said, copying and modifying the `titles.py` extension (as suggested above) is probably easier and cleaner.
