### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by mvcoding** [feincms/feincms#651]
Hey,

will FeinCMS support Django 1.11 in the near future?

**Comment by matthiask** [comment]
Did you run into any problems? I just tested locally, and FeinCMS 1.13.1 and Django 1.11 seem to work well together?

**Comment by mvcoding** [comment]
Sounds good, i will give it a try then and report back if i encounter any problems.

**Comment by matthiask** [comment]
Cool, thanks in advance!

**Comment by mvcoding** [comment]
I haven't found any problems after the upgrade, so we can close this for now.
