### ISSUE TITLE
Django 2.0

### ISSUE THREAD

**Issue by danpalmer** [feincms/feincms#656]
Could the maintainers possible give an update on Django 2.0 support?

 - Will FeinCMS be supporting Django 2.0?
 - Has work begun anywhere (and how can people contribute)?
 - Is there a rough timeline?

**Comment by matthiask** [comment]
Hey,

- Yes, Django 2.0 will be supported.
- Not yet, except for https://github.com/feincms/feincms/commit/c81ef4f817401ead9b0f44c18cb44310e0265354 and https://travis-ci.org/feincms/feincms/builds/288151755 (the build is all-green except for builds against Django's 2.1 branch)
- As always I'll try releasing a compatible FeinCMS version no later than a few days after Django's release (and, if possible, much sooner)

That being said, 1.13.4 might just work with Django 2.0. Feedback on this would be very welcome!

**Comment by mjl** [comment]
My status is that I'm running very much behind, I still have to maintain and develop for sites that run on Django 1.6 ― but if if someone comes up with patches for newer Django versions, I'm all for it!

**Comment by danpalmer** [comment]
No problem, I appreciate the response and it’s great to know you’re dedicated to 2.0 compatibility. 

Out of interest, how thorough do you feel the test suite is? I can’t commit to anything, but I might be able to submit some PRs if I find anything during our Django 2 upgrade, but our use of FeinCMS isn’t particularly exhaustive—can I trust the test suite to catch issues?

**Comment by mjl** [comment]
> Out of interest, how thorough do you feel the test suite is?

  It is probably not thorough enough. I guess it catches some of the strange edge cases that were fixed at some time, and many of the "obvious behaviour" stuff, but they are by no means exhaustive.

  If you run into some problem and the tests don't catch it, by all means, open an issue about it. Though it would be even better if you attached a patch for it (hint hint nudge nudge :-)

  Really, don't feel shy. Contributions are welcome!
