### ISSUE TITLE
Superfluous migrations from indeterminate ordering of ApplicationContent.urlconf_path choices

### ISSUE THREAD

**Issue by yourcelf** [feincms/feincms#657]
The ApplicationContent `urlconf_path` [field definition](https://github.com/feincms/feincms/blob/bc606fdd9989289d697094ed9f64a6d4a25c7048/feincms/content/application/models.py#L214-L218) obtains its choices from an unordered `ALL_APPS_CONFIG` dict, and as a result, superfluous automatic migrations are requested by Django when the in-memory ordering changes, even when there have been no changes to code.

This could be fixed by either sorting the choices, e.g.:

```
        cls.add_to_class(
            'urlconf_path',
            models.CharField(_('application'), max_length=100, choices=[
-                (c['urls'], c['name']) for c in cls.ALL_APPS_CONFIG.values()])
+                (c['urls'], c['name']) for c in sorted(cls.ALL_APPS_CONFIG.values())])
        )
```

or by changing `ApplicationContent.ALL_APPS_CONFIG` to be an ordered dict instead.
```
class ApplicationContent(models.Model):
    ...

-    ALL_APPS_CONFIG = {}
+    ALL_APPS_CONFIG = OrderedDict()
```

**Comment by matthiask** [comment]
Thanks for the report! `collections.OrderedDict` is already being used in FeinCMS, so that would probably be the best fix. Do you want to submit a pull request?

**Comment by yourcelf** [comment]
Thanks for fixing. Hadn't found the spare minute to open a PR. :)

**Comment by MRigal** [comment]
Looking forward for a new version including the fix!

**Comment by matthiask** [comment]
Thanks for the reminder, I just uploaded v1.13.5 to PyPI :-)
