### ISSUE TITLE
Reverting to a previous version no longer works with Reversion 2.0+

### ISSUE THREAD

**Issue by djowett** [feincms/feincms#661]
Simply put the page is a mess because the JS rearranges it.
I hope to put a fixing PR up tomorrow  

A picture is worth a thousand words

![feincms history broken on reversion upgrade public](https://user-images.githubusercontent.com/1470021/33348980-28b4995e-d490-11e7-96bc-9f64070988eb.png)

**Comment by mjl** [comment]
Oh, the reversion module hasn't aged well it seems. It definitely could use some TLC, thanks for looking into it!

  I've seen such things happen but it mostly was when upgrading to a new version of feincms and the browser using a cached older version of the js for the admin pages, or me forgetting to collectstatic. That is, what you are seeing is the state of the page *before* the js rearranges it (yes, the admin interface is a little bit of a hack). I guess something structural has changed in the page and the js can't find the components any more, so it doesn't know what to do.

**Comment by djowett** [comment]
Thanks @mjl, that's more or less correct, but the page is neater before JS fires (I can send screenshot if you like), but anyway the fix for that is [here](https://github.com/djowett/feincms/commit/1062bb925c441e34fa51e162d4da53921495254e) but other issues stop this being a final fix.

**Comment by djowett** [comment]
@mjl Below is a page (different blog post) with JS disabled.  I have got the other issue fixed too, so will get 2 PRs submitted today

![feincms history broken on reversion upgrade javascript disabled](https://user-images.githubusercontent.com/1470021/33428039-4c7d530a-d5bf-11e7-9890-91dd1326d358.png)

**Comment by djowett** [comment]
Further trying to click Save on the page raises a NoReverseMatch:

`Reverse for 'app_list' with arguments '('',)' and keyword arguments '{}' not found.`

**Comment by djowett** [comment]
@matthiask can i ask your view on this? IIUC you don't use FeinCMS with Reversion, but my experience is that it is simply broken when trying to use latest Reversion (2.0)

**Comment by matthiask** [comment]
@djowett I don't know the code very well since - as you noticed - I'm not using reversion.

We are using `changelist_url` in our templates, and I can't find this variable in FeinCMS, Django or django-reversion. I'm wondering where this variable would come from? Same with `app_label`. Everyone else just passes `Model._meta` as `opts` and uses `|admin_urlname` and friends afterwards.

```
feincms/templates/admin/feincms/recover_form.html:9:                <a href="{{changelist_url}}">{{opts.verbose_name_plural|capfirst}}</a> &rsaquo;
```

Reversion 2.0 has been released in June 2016, maybe it would be best to drop compatibility with Reversion<2 for the next release of FeinCMS and rewrite the reversion templates from ground up?

**Comment by djowett** [comment]
@matthiask thanks for the reply!  `changelist_url` is defined twice in [this file](https://github.com/etianen/django-reversion/blob/release-1.8.6/src/reversion/admin.py#L193) but it seems to disappear in 1.9+ (having been there since at least 1.3.3).

https://github.com/etianen/django-reversion/issues/445 is quite informative for changes required in other products which moved to Reversion 1.9 from a previous version.

Not sure about the compatibility issue, we are moving forward, but have only one deployment to support, but I would think that others might be restricted in their options. @mjl ?

**Comment by mjl** [comment]
I can't really contribute as I too, am not using reversion. 

>From your perspective, how intrusive is upgrading von reversion < 2 to reversion >= 2, on the reversion data side? Does all hell break lose with your data, do you lose your history? Or is it simply a "manage.py migrate"?

If upgrading reversion can be summarized as "do these three steps and you're done" then I see no problem with mandating reversion >= 2.

**Comment by djowett** [comment]
@mjl the reversion migration could be better in our view, as it removes fields at the same time as doing other structural and data changes (and then squashes them together). This means that the Reversion migration status has to match the Reversion code status - and therefore upgrades require a small 'maintenance window' there's no "phased approach" that would help in this, though I guess this does simplify support issues for Reversion.   

However, given that, I've not seen any loss of data history (note we were using only one 'manager' and are only Versioning one 'db', so this is not the most complex setup).  Other than the above gripe, migration is straightforward - but if you need to rollback then it is fiddly (need to delete the squashed migration) and you at that moment will most likely wish the removed fields and their data were still there.  This is of course a 'pure' Reversion gripe,  nothing to do with FeinCMS.

We have yet to move this to production - we were hoping to ensure that PR gets merged and a release gets tagged first, but I guess that's a chicken & egg situation?

I can't guarantee I've solved all issues with taking Reversion 2.0, but I think FeinCMS needs to bite this bullet soon, as if users of both FeinCMS and Reversion want to upgrade Django past 1.8.x then they will need _at least_ Reversion 1.10 (implied from [here](https://github.com/etianen/django-reversion/issues/454), but probably 2.0.x), but FeinCMS currently doesn't work with Reversion 1.10 or 1.9 (as mentioned [above](https://github.com/feincms/feincms/issues/661#issuecomment-349919052)).
So without this PR FeinCMS is unfortunately blocking these users from upgrading past Django 1.8.

**Comment by mjl** [comment]
Well, if it's reasonably safe, and furthermore those old reversion versions are no longer useful with a recent django, then I'd say let's go for it. Matthias?

**Comment by matthiask** [comment]
Yes, sounds good!

**Comment by djowett** [comment]
That's great. What's the next step?

**Comment by mjl** [comment]
@matthiask: will you do the merge? You're the boss here :-)

@daniel: do you have (or could you write) a short blurp about what
changed, why it changed, what people need to do if they use reversion?
Something to put in the release notes, pretty please? Doesn't need to be
an epic tale, so don't worry if it's just three sentences!

**Comment by djowett** [comment]
@mjl sure. How's this?

Fixed history (revision) form, recover form and breadcrumbs when FeinCMS is used with Reversion 2.0.x.  This accommodates refactoring that took place in Reversion 1.9 and 2.0.  If you are upgrading Reversion (rather than starting a new project), please be aware of the significant interface changes and database migrations in that product, and attempt upgrading in a development environment before upgrading a live site.

**Comment by mjl** [comment]
Great, thanks! Is there a web page somewhere with "upgrade to reversion 2.0 from reversion 1.x" instructions that you feel are useful and we should link to?

**Comment by djowett** [comment]
@mjl Np, I think the best/definitive place to go for that is https://django-reversion.readthedocs.io/en/stable/changelog.html
