### ISSUE TITLE
Increase max_length of MediaFileTranslation captions?

### ISSUE THREAD

**Issue by typeshige** [feincms/feincms#666]
Hi,

I'm wondering if there are any issues with setting the max_length of captions in MediaFileTranslation from 200 to something much larger?

I have a fork of FeinCMS where the only change is we are setting the max_length to 1024.

Assuming this doesn't cause any new issues, I'd love for a longer max_length.

Thanks.

**Comment by matthiask** [comment]
We can probably assume that everyone has migrations in place these days, so this change shouldn't hurt anyone.

@mjl Do you have any reservations?

**Comment by mjl** [comment]
No, go ahead. Even if people are not migrating, it will not cause any immediate problems (ie. nothing blows up if you run against an unmigrated db, and will most likely continue to run).

**Comment by matthiask** [comment]
@mjl Thanks!
@typeshige Do you want to submit a pull request?

**Comment by typeshige** [comment]
#668

Here you go.  Thanks.
