### ISSUE TITLE
The `process` method of custom page model isn't called.

### ISSUE THREAD

**Issue by barseghyanartur** [feincms/feincms#671]
I have a custom Page model.

```python
from feincms.models import create_base_model
from mptt.models import MPTTModel
class Location(create_base_model(MPTTModel)):
   # ... other things
```

I have a widget [fobi.contrib.apps.feincms_integration.widgets.FobiFormWidget](https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/apps/feincms_integration/widgets.py) which works fine with standard FeinCMS page (the `process` method of the `FobiFormWidget` is being called).

However, when I try to use the FobiFormWidget with custom page model (`Location`), it doesn't work (`process` method is never called).

So, the following parts of the widget work fine with standard FeinCMS Page.

```python
    def process(self, request, **kwargs):
        """This is where most of the form handling happens.

        :param django.http.HttpRequest request:
        :return django.http.HttpResponse | str:
        """
        return self._process(request, self, **kwargs)

    def render(self, **kwargs):
        """Render."""
        return getattr(self, 'rendered_output', ''):

    def finalize(self, request, response):
        """Finalize."""
        # Always disable caches if this content type is used somewhere
        response['Cache-Control'] = 'no-cache, must-revalidate'
```

But it does not work on the custom page (`Location`).

I do get into `render` method of the widget, but I need to handle redirects as well and as far as I understand, `render` method doesn't handle that part.

I do get things like this in my HTML:

```html
<HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/locations/mylocation/subscribe-form-page/?sent=form-sent">
```

Any tips would be very useful. Thanks!

**Comment by matthiask** [comment]
Are you using `ContentView` or `ContentObjectMixin` in your `Location` view? `ContentObjectMixin.handler` contains all the necessary steps to support `process()` and `finalize()`:
https://github.com/feincms/feincms/blob/master/feincms/module/mixins.py#L81

**Comment by barseghyanartur** [comment]
@matthiask:

Thanks! I'll try.
