### ISSUE TITLE
Admin site JS does not work in Django 2.1

### ISSUE THREAD

**Issue by danpalmer** [feincms/feincms#673]
We've just upgraded to 2.1, and assumed that FeinCMS was compatible given it's requirements bounds, but we're seeing JS errors when trying to add new content elements to a page. This makes it impossible to create new pages, and to do much editing on existing pages.

The error in the browser console is:

```
TypeError: undefined is not an object (evaluating 'form.attr')
```

<img width="460" alt="screen shot 2018-08-27 at 12 42 32" src="https://user-images.githubusercontent.com/202400/44657962-b3e55400-a9f6-11e8-8a7b-4a32e7d1dde1.png">

I can reproduce this in the latest public/stable builds of Safari and Chrome.

**Comment by danpalmer** [comment]
I can reproduce this in the latest public/stable builds of Safari and Chrome.

**Comment by danpalmer** [comment]
More investigation, this is specifically the `create_new_spare_form` function that fails. It seems like no additional forms are being created, most likely because the Django structure of the admin pages has changed.

```js
    function create_new_spare_form(modvar) {
        var old_form_count = parseInt($('#id_'+modvar+'_set-TOTAL_FORMS').val(), 10);
        // **** UGLY CODE WARNING, avert your gaze! ****
        // for some unknown reason, the add-button click handler function
        // fails on the first triggerHandler call in some rare cases;
        // we can detect this here and retry:
        for(var i = 0; i < 2; i++){
            // Use Django's built-in inline spawing mechanism (Django 1.2+)
            // must use django.jQuery since the bound function lives there:
            django.jQuery('#'+modvar+'_set-group').find(
                'div.add-row > a').triggerHandler('click');
            var new_form_count = parseInt($('#id_'+modvar+'_set-TOTAL_FORMS').val(), 10);
            if(new_form_count > old_form_count){
                return $('#'+modvar+'_set-'+(new_form_count-1));
            }
        }
    }
```

How could this be refactored to not use the Django behaviour? Relying on the Django provided page structure is private API, and it also feels like an implementation detail that is likely to change frequently and without warning.

**Comment by matthiask** [comment]
Hmm, thanks for investigating. The django-content-editor method still seems to work (https://github.com/matthiask/django-content-editor/blob/8396cd797654056d5e676f802a1e99976d17102c/content_editor/static/content_editor/content_editor.js#L10) so maybe the `div.add-row>a` selector is too specific?

Anyway. Django's inlines.js (https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/inlines.js) does not provide an API, so I don't immediately see how we could do better in this area.

**Comment by danpalmer** [comment]
There's also a bug in `AdminFileWithPreviewWidget` - it needs to accept args/kwargs. I'm probably going to open a PR for that soon.

**Comment by danpalmer** [comment]
For now, it might be worth reducing the version bounds of FeinCMS to stop anyone else bumping into this - we're now trying to patch production because our content team are unable to work since we upgraded to Django 2.1.

**Comment by mjl** [comment]
Yes, agreed, we are intruding in a somewhat private Django thing; the reason was to leverate the auto generated change_form mechanism and not rewrite it entirely.

> How could this be refactored to not use the Django behaviour? Relying
> on the Django provided page structure is private API, and it also
> feels like an implementation detail that is likely to change
> frequently and without warning.

**Comment by matthiask** [comment]
@danpalmer Is it possible for you to test the master branch with your site?

Here, I made the .add-row selector less specific:
https://github.com/feincms/feincms/commit/8e74ceb6b64294a6b96084fe7317e006fe9e8094

Also, Django 2.1 requires a new stacked inline template:
https://github.com/feincms/feincms/commit/5008e4eb3bb4762c0d6c2af57bd1ff7765edfd02

If it works I'll upload a release right away.

**Comment by danpalmer** [comment]
Perfect! Works for me!

**Comment by matthiask** [comment]
👍 v1.14.2 contains the fixes.

**Comment by danpalmer** [comment]
Just to close this off, we’ve deployed the new version and everything is working fine. 

Thanks for the quick response and fixes!
