### ISSUE TITLE
Concurrent editing of pages

### ISSUE THREAD

**Issue by vmax** [feincms/feincms#678]
What's the best way to approach the problem in title with FeinCMS?

**Comment by matthiask** [comment]
There isn't an established best way of doing this yet, I think neither in Django nor in FeinCMS.

**Comment by barseghyanartur** [comment]
See this:

https://djangopackages.org/grids/g/concurrent-edit/

**Comment by vmax** [comment]
@matthiask @barseghyanartur thank you for your help!
