### ISSUE TITLE
No changes for CHANGELOG.rst

### ISSUE THREAD

**Issue by DmytroLitvinov** [feincms/feincms#681]
There is no changes in the file `CHANGELOG.rst`

**Comment by matthiask** [comment]
I'm not sure what you're referring to. It seems to work fine for me https://github.com/feincms/feincms/blob/master/CHANGELOG.rst

Please reopen if the problem persists. Thanks!

**Comment by DmytroLitvinov** [comment]
I was referring to changes that were not included in that file. Right now I see it is okay. Thanks.
