### ISSUE TITLE
Custom page insertion order

### ISSUE THREAD

**Issue by vmax** [feincms/feincms#688]
What would be the way to add `order_insertion_by` to `Page` model (via `MPTTMeta`) besides forking the library and modifying the source?

[This](https://github.com/Trounceflow/feincms/commit/65004e2ff6cd667bf41846ad0155b5ba0a66b3ca.patch) is the type of changes I'd like to apply.

**Comment by matthiask** [comment]
(Unfortunately) FeinCMS already uses monkey patching in various places, so maybe adding `Page._mptt_meta.order_insertion_by = ["title"]` somewhere works? I'd try adding it in the same file as `Page.register_templates`, `Page.create_content_type` etc.
