### ISSUE TITLE
Migrate old release notes to changelog

### ISSUE THREAD

**Issue by MRigal** [feincms/feincms#691]
It is a bit disturbing to have (only) the release notes of the old versions in the docs at https://feincms-django-cms.readthedocs.io/en/latest/. IMHO it should be moved to https://github.com/feincms/feincms/blob/master/CHANGELOG.rst

Also the changelog could (or should?) be added to the documentation

**Comment by matthiask** [comment]
Yes, and yes! Thanks for the idea.

The changelog is now integrated into the documentation: https://feincms-django-cms.readthedocs.io/en/latest/

Fixed in https://github.com/feincms/feincms/commit/cc6cc8acd4126241a9002c3624081562ebf849d4

**Comment by MRigal** [comment]
That was a lightning fix!!! I've allowed myself to add a comment to your fix
