### ISSUE TITLE
FeinCMS==1.10.1 is not working with Django==1.6.8

### ISSUE THREAD

**Issue by SharmaHimanshu1991** [feincms/feincms#694]
Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2

I am to implement all this on above python 2.7.17 version.
 
I am getting the error of TinyMCE  at admin side. Below you can find error. 
**Your access to TinyMCE will expire on 30 November 2020. Please either contact your administrator or upgrade your account using the instructions available at https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.**

As per my research TinyMCE is come by default with FeinCMS. As I am updating FeinCMS==1.10.1 to FeinCMS ==1.18.0 latest version then my project is not working and I also update the "//tinymce.cachefly.net/4.1/tinymce.min.js" to "//tinymce.cachefly.net/5.1/tinymce.min.js" but this is also not resolved my above error. 

I follow the step given in  above error URL "https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/"  but this also not helping me.
Please provide me any solution will be appreciated.

**Comment by matthiask** [comment]
See https://github.com/feincms/feincms/commit/fe919ad7f8b791ee509410833ffbfd5645061a26 – reconfiguring the `TINYMCE_JS_URL` worked for me.

**Comment by SharmaHimanshu1991** [comment]
I am working on  Django==1.6.8,  FeinCMS==1.10.1
Python 2.7.17 (default, Sep 30 2020, 13:38:04)
[GCC 7.5.0] on linux2

All  packages of this project is installed in virtual environment.
As per your **fe919ad** reference. I had made a change in env/lib/python2.7/site-packages/feincms/default_settings.py file 

**from** 

FEINCMS_RICHTEXT_INIT_CONTEXT = getattr(
    settings,
    'FEINCMS_RICHTEXT_INIT_CONTEXT', {
        'TINYMCE_JS_URL': '//tinymce.cachefly.net/4.1/tinymce.min.js',
        'TINYMCE_DOMAIN': None,
        'TINYMCE_CONTENT_CSS_URL': None,
        'TINYMCE_LINK_LIST_URL': None
    }
)

**to**

FEINCMS_RICHTEXT_INIT_CONTEXT = getattr(
    settings,
	"FEINCMS_RICHTEXT_INIT_CONTEXT",{
		"TINYMCE_JS_URL": "//tinymce.cachefly.net/4.2/tinymce.min.js",
		"TINYMCE_JS_URL": "https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.11/tinymce.min.js",  # noqa
		"TINYMCE_DOMAIN": None,
		"TINYMCE_CONTENT_CSS_URL": None,
		"TINYMCE_LINK_LIST_URL": None,

    }
)

But I am getting error -→
**Your access to TinyMCE will expire on 30 November 2020. Please either contact your administrator or upgrade your account using the instructions available at https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.**

**Comment by matthiask** [comment]
You shouldn't edit files inside the virtualenv; they may get overwritten when deploying the project the next time.

Here's what you could do. Add the following lines to your settings, maybe replacing other `FEINCMS_*` settings while doing this:

```
TINYMCE_JS_URL = "https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.11/tinymce.min.js"
FEINCMS_RICHTEXT_INIT_CONTEXT = {"TINYMCE_JS_URL": TINYMCE_JS_URL}
FEINCMS_RICHTEXT_INIT_TEMPLATE = "admin/content/richtext/init_tinymce4.html"
```

**Comment by SharmaHimanshu1991** [comment]
Thanks a lot.
 By adding these  above lines in my project settings.py file my error is resolved.

I had only 
FEINCMS_USE_PAGE_ADMIN = False
FEINCMS_DEFAULT_PAGE_MODEL = 'pages.Page'
 and  
    'feincms',
    'mptt',
    'feincms.module.page',
    # 'feincms.module.medialibrary',

added in INSTALLED_APPS in my settings.py file only. 

Can you explain me brief what these line which you provided is doing?

**Comment by matthiask** [comment]
I don't know why you'd have to reconfigure the page model.

The lines I posted above change the URL where TinyMCE is loaded from. The authors added a deprecation warning to the "official" URL, I don't know why, exactly.
