### ISSUE TITLE
ApplicationContent does not pass Cookies to response

### ISSUE THREAD

**Issue by mjl** [feincms/feincms#706]
I recently had an issue with an ApplicationContent, which did set a cookie (in this case a csrf_token), but that cookie never appeared in the response.

I tracked down the problem to feincms/content/application/models.py, which in `_update_response_headers()` does not care for cookies, and in `process()` doesn't either.

I've come up with a simple patch, but I am unsure whether that will work with Django < 4.2 or older python versions, since I have no idea whether those versions also use `http.cookies.Morsel` to represent cookies.

For the record, here is the patch

```patch
--- models.py.orig	2023-07-20 13:07:20.851380699 +0200
+++ models.py	2023-07-20 13:14:18.409153238 +0200
@@ -354,6 +354,10 @@
                     if h in output:
                         self.rendered_headers.setdefault(h, []).append(output[h])

+                application_cookies = output.cookies
+                if application_cookies:
+                    self.rendered_headers['X-Feincms-Cookie'] = application_cookies
+
         elif isinstance(output, tuple) and "view" in kw:
             kw["view"].template_name = output[0]
             kw["view"].request._feincms_extra_context.update(output[1])
@@ -420,6 +424,15 @@
         if len(lm_list) > 0:
             response["Expires"] = http_date(mktime(min(lm_list)))

+        # Add all cookies
+        cookies = headers.get('X-Feincms-Cookie', None)
+        if cookies:
+            for kookie, val in cookies.items():
+                response.set_cookie(kookie, value=val.value,
+                        max_age=val['max-age'], expires=val['expires'], path=val['path'],
+                        domain=val['domain'], secure=val['secure'], httponly=val['httponly'],
+                        samesite=val['samesite'])
+
     @classmethod
     def app_reverse_cache_key(self, urlconf_path, **kwargs):
         return "FEINCMS:{}:APPCONTENT:{}:{}".format(
```

Perhaps it needs some guards against older implementations of cookies and could be merged?

**Comment by matthiask** [comment]
Django has been using `http.cookie` for a really long time, see https://github.com/django/django/commit/2b281cc35ed9d997614ca3c416928d7fabfef1ad#diff-53ebbe2eee45e69ba2a4a071d31269c34e4640cf61f613e95512a7b9d421a3db

We do not support `Django<3.2` anymore, so relying on `http.cookie` is safe.

**Comment by mjl** [comment]
Cool, thanks for the research!

  So ok to add (if I add a test case for it), or do you have any concerns?

**Comment by matthiask** [comment]
No concerns, thanks for doing this!
