### ISSUE TITLE
Category filter in MediaFile admin raises TypeErrror w/ Django 5

### ISSUE THREAD

**Issue by mjl** [feincms/feincms#714]
Selecting a category in django admin > MediaFile yields
 
> File "/Users/mjl/Projects/repos/feincms/feincms/admin/filters.py", line 99, in choices
    "selected": pk == int(self.lookup_val or "0"),
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

I think it is related to this:

> The django.contrib.admin.AllValuesFieldListFilter, ChoicesFieldListFilter, RelatedFieldListFilter, and RelatedOnlyFieldListFilter admin filters now handle multi-valued query parameters.

And the fix is to copy the appropriate line over from Django's codebase. However, that will not work with Django<4 (or at least not work reliably). Should I add a `if instance(self.lookup_val, (str, int))` or better trigger off the Django version?

```diff
index dc77ce9a..6b51c824 100644
--- a/feincms/admin/filters.py
+++ b/feincms/admin/filters.py
@@ -54,7 +54,7 @@ class ParentFieldListFilter(ChoicesFieldListFilter):

         for pk, title in self.lookup_choices:
             yield {
-                "selected": pk == int(self.lookup_val or "0"),
+                "selected": self.lookup_val is not None and str(pk) in self.lookup_val,
                 "query_string": cl.get_query_string({self.lookup_kwarg: pk}),
                 "display": mark_safe(smart_str(title)),
             }
@@ -96,7 +96,7 @@ class CategoryFieldListFilter(ChoicesFieldListFilter):

         for pk, title in self.lookup_choices:
             yield {
-                "selected": pk == int(self.lookup_val or "0"),
+                "selected": self.lookup_val is not None and str(pk) in self.lookup_val,
                 "query_string": cl.get_query_string({self.lookup_kwarg: pk}),
                 "display": mark_safe(smart_str(title)),
             }
```

**Comment by matthiask** [comment]
I have had the same issue in django-cabinet and have fixed it with a `django.VERSION > (5,)` check. I think it's clearer to use a branch depending on `VERSION` than on the datastructure.
https://github.com/matthiask/django-cabinet/blob/main/cabinet/base_admin.py

**Comment by mjl** [comment]
Note for future: Perhaps some of the (severely underdocumented) django.contrib.auth.filters like `RelatedFieldListFilter` could be used instead of rolling our own.
