### ISSUE TITLE
TypeError "Cannot combine a unique query with a non-unique query" in treeeditor

### ISSUE THREAD

**Issue by mjl** [feincms/feincms#716]
One of my CTs is exploding in the admin interface when clicking on the loupe icon on raw_id foreigh key fields. This opens a popup window with the URL `https://.../admin/page/page/?magazinearticlecontent_set__isnull=0&_to_field=id`. This query then throws an exception

```
Exception Type: TypeError at /admin/page/page/
Exception Value: Cannot combine a unique query with a non-unique query.
Raised during: feincms.module.page.modeladmins.changelist_view
Request information:
USER: admin

GET:
magazinearticlecontent_set__isnull = '0'
_to_field = 'id'
_popup = '1'
```

I traced it to `..../lib/python3.10/site-packages/feincms/admin/tree_editor.py`, line 176

```python
self.queryset |= self.model._default_manager.filter(
     reduce(lambda p, q: p | q, clauses)
)
```

After some googling, I came to using `union` instead, however that loses the sort order, so I had to re-sort

```python
self.queryset = self.queryset.union(
    self.model._default_manager.filter(
        reduce(lambda p, q: p | q, clauses)
)).order_by('tree_id', 'lft')
```

This makes things work again, but I am unsure whether that is the correct fix as I'm not familiar with the code, and repeating the sorting feels not quite right.

**Comment by matthiask** [comment]
This looks correct to me. Just one small detail: We're using `.order_by(mptt_opts.tree_id_attr, mptt_opts.left_attr)` in `_build_tree_structure` so we should probably do the same here. It's one of the unfortunate design decisions of django-mptt to make those field names configurable.
